### ISSUE TITLE
POI subclass icons not used ?

### ISSUE THREAD

**Issue by etienneJr** [lukasmartinelli/osm-liberty#146]
Hello,

(I previously posted this as a comment in issue #113 but since it is closed I prefer to open a new issue)

Since issue #113 the expression `"icon-image": ["match", ["get", "subclass"], ["florist", "furniture"], ["get", "subclass"], ["get", "class"]]` is used to try to find the subclass icon of a POI instead of the class icon (right?)

It seems to me that this is not working in the case of the sport icon (subclass) versus the pitch icon (class).

(In the 2 examples below, I printed the subclass instead of the name in the text layout field, and the captures are from maputnik website)

For example, I was expecting the match expression to give this result, with different icons for soccer and tennis pitches:
![360673350-620d4d35-fc97-4385-ba1e-d92366fe7e01](https://github.com/user-attachments/assets/f4ee085d-ee15-4a88-9c7b-20dd96b11271)
(To get this result I had to used `"icon-image": "{subclass}"` which is not satisfactory because it does not have the fallback)

whereas the match expression gives this result, with always the pitch icon whatever the sport:
![360674080-ab6dc69e-a9da-4315-a775-b971ba45333f](https://github.com/user-attachments/assets/cf3f53d1-d121-4efc-9928-8a0c6e7c1bf0)

I did not check if it is working for other subclass icons (when the class is not pitch).

**Comment by etiennejourdier** [comment]
I did other tests and noticed that the `match` expression never works, it always returns the fallback value.
For example, even `["match", "pitch", "soccer", "tennis", "bakery"]` does not work, it should display the pitch icon but it displays the bakery icon.

**Comment by pathmapper** [comment]
> Since issue https://github.com/maputnik/osm-liberty/issues/113 the expression "icon-image": ["match", ["get", "subclass"], ["florist", "furniture"], ["get", "subclass"], ["get", "class"]] is used to try to find the subclass icon of a POI instead of the class icon (right?)

In general, yes, but the above expression only takes into account the subclass 'Florist' and the subclass 'Furniture'. 

From https://github.com/maputnik/osm-liberty/issues/64#issuecomment-1773818116 :

> Contributions also for POI subclass welcome, see https://github.com/maputnik/osm-liberty/pull/119 for an example.

To style other subclass values we need,
a) an icon in the sprites
b) add the subclass to the match expression.



Since both icons for tennis/soccer are already included in the sprites, I added them in https://github.com/maputnik/osm-liberty/pull/147.

**Comment by etienneJr** [comment]
Thanks @pathmapper for the explanation, and for the PR!
I noticed that a few other sport sprites already exist but are not used yet, could you add them as well in the list ?
- american_football, baseball, basketball, cricket: in `subclass`
- swimming_pool : in `class` but the sprite is named swimming

But I also wonder: why not use the more general expression `["coalesce", ["get", "subclass"], ["get", "class"]]`? It works fine for pitches. Does it cause problems for other classes?
