### ISSUE TITLE
shop=butcher lacks any icon

### ISSUE THREAD

**Issue by RicoElectrico** [lukasmartinelli/osm-liberty#2]
There's only a label displayed.

**Comment by lukasmartinelli** [comment]
Thanks @RicoElectrico 

https://github.com/osm2vectortiles/osm2vectortiles probably doesn't have a maki icon for the butcher. we need to add it there.

**Comment by orangemug** [comment]
We could probably use https://github.com/mapbox/maki/blob/master/icons/slaughterhouse-15.svg as openmaptiles doesn't have a POI for a slaughterhouse (see https://github.com/openmaptiles/openmaptiles/blob/b28ea79d4c7fa62ee6d7c19e1644b10b6c59b629/layers/poi/mapping.yaml)
