### ISSUE TITLE
Self Host Tiles

### ISSUE THREAD

**Issue by schwiet** [lukasmartinelli/osm-liberty#20]
The Readme seems to imply that I can 

> host the tiles and assets yourself for complete liberty.

But the tiles don't appear to be in the repo. Have I misunderstood the intent? I see that the tiles are being served from a free, non-commercial-use CDN, but what if I do want to serve them myself, say offline?

**Comment by klokan** [comment]
The project uses OpenMapTIles - see https://openmaptiles.org/, where you can download the tiles for free or generate them yourself...

**Comment by orangemug** [comment]
Thanks @klokan closing issue
