### ISSUE TITLE
Update repo description and website

### ISSUE THREAD

**Issue by pathmapper** [lukasmartinelli/osm-liberty#29]
![auswahl_340](https://user-images.githubusercontent.com/20856381/42453847-3a8eef14-838e-11e8-9d07-cf856e168d3e.png)

@orangemug could you please update the repo description, maybe "A free Mapbox GL basemap style for everyone" (added the word "style") and remove or update the link. Because of the missing repo key a preview is working only via https://maputnik.github.io/editor/?style=https://rawgit.com/maputnik/osm-liberty/gh-pages/style.json, which may be too long here.

**Comment by orangemug** [comment]
Done
