### ISSUE TITLE
highway=pedestrian area=yes is styled as line

### ISSUE THREAD

**Issue by RicoElectrico** [lukasmartinelli/osm-liberty#3]
I don't know whether the problem lies upstream in osm2vt.
Example: http://osm-liberty.lukasmartinelli.ch/#17.78/52.23858/20.99521

**Comment by lukasmartinelli** [comment]
Thanks. Yup upstream. But it's ok since it is my fault either way ;)

https://github.com/osm2vectortiles/osm2vectortiles/issues/114
