### ISSUE TITLE
Getting 404 error when trying to access glyphs url

### ISSUE THREAD

**Issue by donnyv** [lukasmartinelli/osm-liberty#30]
Looks like the glyphs are missing.
https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf

![image](https://user-images.githubusercontent.com/2224189/45176416-ee60a500-b1dd-11e8-85d5-fe68d35d242e.png)

**Comment by orangemug** [comment]
It looks like you're not using the default osm-liberty version. osm-liberty relies on the Roboto typefaces. These requests are asking for 'Open Sans'

**Comment by donnyv** [comment]
I'm using the style.json from this github readme. 
https://maputnik.github.io/osm-liberty/style.json

When I remove a place holder key. It asks for one also.
![image](https://user-images.githubusercontent.com/2224189/45322427-33eedc00-b516-11e8-8363-bb0914a0d2e5.png)

If this isn't right. What is the proper style url?

**Comment by pathmapper** [comment]
> I'm using the style.json from this github readme.
> https://maputnik.github.io/osm-liberty/style.json

@donnyv the style URL is correct, but there is no public key available anymore (the readme needs an update, thanks for mentioning this). 

You would need to replace the placeholder _{key}_ here https://github.com/maputnik/osm-liberty/blob/gh-pages/style.json#L19 with your own key for [Maptiler Cloud](https://www.maptiler.com/cloud/plans/) or you could use the osm-liberty style with your own vector tiles created with [OpenMapTiles](https://openmaptiles.org/).

**Comment by donnyv** [comment]
I have a question. If I didn't want any basemap but wanted to use your glyphs. How would I do that?

This is what I have now but it seems mapbox-gl-js asks for Arial by default.

```
var map = new mapboxgl.Map({
	container: "map",
	center:[-74.1064844188952, 40.688910122845137],
	zoom: 17,
	
	style: {
		"version": 8,
		"glyphs": "https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf",
		"sources": {},
		"layers": [
			{
			  "id": "background",
			  "type": "background",
			  "paint": {
				"background-color": "hsl(0, 0%, 0%)"
			  }
			}
		]
	}
});
```
![image](https://user-images.githubusercontent.com/2224189/45363909-c2ab3980-b5a6-11e8-9dd4-37042c131a6e.png)

Example
http://gis2.civilsolutions.biz/mapboxbug/map.htm

**Comment by pathmapper** [comment]
@donnyv you need to specify the font you want to use with the [`text-font` layout property](https://www.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-text-font), e.g.:

`'text-font': ['Roboto Regular']`

Your example:
http://jsbin.com/behoruwapa/edit?html,output

**Comment by donnyv** [comment]
How did I miss that! Thanks!
