### ISSUE TITLE
Provide font metadata

### ISSUE THREAD

**Issue by pathmapper** [lukasmartinelli/osm-liberty#36]
Motivation:
- To prevent confusion when using the style with Maputnik. Currently there is a 404/warning logged because there is no metadata file available for 
`https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf` :
![auswahl_423](https://user-images.githubusercontent.com/20856381/45932790-2c9de880-bf82-11e8-994f-acf221eaa5e6.png)

- To benefit from Maputnik's ability to show available fonts, e.g. this is how it looks with 
`http://fonts.openmaptiles.org/{fontstack}/{range}.pbf`, there is a [metadata file](https://github.com/openmaptiles/fonts/blob/gh-pages/fontstacks.json) available:
![font_preview](https://user-images.githubusercontent.com/20856381/45932857-68857d80-bf83-11e8-8449-6c9accb19af1.gif)
This might be helpful in a case like https://github.com/maputnik/osm-liberty/issues/30.

Some thoughts about possible options:
1. Add a metadata file to https://github.com/orangemug/font-glyphs.
2. Use https://github.com/orangemug/font-glyphs-v2 if Maputnik would be able to use such [metadata](https://github.com/orangemug/font-glyphs-v2/blob/gh-pages/glyphs/index.json).
3. Use `https://maps.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}`. There is metadata available and we use Maptiler Cloud also as default for the tiles.

//cc @orangemug

**Comment by orangemug** [comment]
Since we use `tilehosting.com` for the data source, I think it makes sense to use it for the glyphs also. So I like option 3

**Comment by pathmapper** [comment]
Thanks for your feedback @orangemug ! 

Done in https://github.com/maputnik/osm-liberty/pull/37.

**Comment by orangemug** [comment]
@pathmapper I also added a `glyphs.json` to https://github.com/orangemug/font-glyphs just incase anybody wants to use it in future.

Note: I still think `tilehosting.com` is the correct solution here.

**Comment by pathmapper** [comment]
@orangemug great! If you change your mind we could revert the switch to `tilehosting.com` of course.  

Your font-glyphs repositories are definately something I would like to cover for a _host the tiles and assets yourself for complete liberty_ section here or better in context of https://github.com/maputnik/editor/issues/337.
