### ISSUE TITLE
Island missing styling

### ISSUE THREAD

**Issue by orangemug** [lukasmartinelli/osm-liberty#41]
<img width="575" alt="screen shot 2018-10-28 at 09 10 57" src="https://user-images.githubusercontent.com/235915/47614057-6e461580-da91-11e8-8f15-b9fa5fc26671.png">

See <https://maputnik.github.io/editor/?style=https://maputnik.github.io/osm-liberty/style.json#11.68/55.7805/11.8296>

**Comment by pathmapper** [comment]
Looks like an issue related to the vector source (https://github.com/openmaptiles/openmaptiles/issues/458 was similar), opened an issue there: https://github.com/openmaptiles/openmaptiles/issues/519

**Comment by pathmapper** [comment]
This has been fixed in the OSM data for zoom level = 8 and above and the changes are now included in the latest Maptiler OMT tileset.

For zoom level < 8 there is another open issue: https://github.com/openmaptiles/openmaptiles/issues/549
