### ISSUE TITLE
Bridges are rendered on top of 3d buildings

### ISSUE THREAD

**Issue by orangemug** [lukasmartinelli/osm-liberty#42]
<img width="334" alt="screen shot 2018-10-24 at 13 22 02" src="https://user-images.githubusercontent.com/235915/47614120-6e92e080-da92-11e8-8c41-3bbc3efc9fbe.png">

https://maputnik.github.io/editor/?style=https://maputnik.github.io/osm-liberty/style.json#15.43/40.711824/-74.014166/0/60

Problem layers

 - bridge_path_pedestrian
 - bridge_path_pedestrian_casing

<img width="432" alt="screen shot 2018-10-28 at 09 18 00" src="https://user-images.githubusercontent.com/235915/47614122-810d1a00-da92-11e8-9021-a13df889a9ca.png">

https://maputnik.github.io/editor/?style=https://maputnik.github.io/osm-liberty/style.json#14.96/40.71394/-74.01451/101.6/60

Problem layers

 - bridge_motorway

It looks to me that the `building*` layers should be above the `bridge*` layers

**Comment by pathmapper** [comment]
> It looks to me that the building* layers should be above the bridge* layers

@orangemug there are also cases where there are bridges above buildings (see below for such an example how it looks if buildings are rendered above bridges), but I think this is less worse than the examples you've posted above, so I'm :+1: for moving the `building*` layers.

![auswahl_433](https://user-images.githubusercontent.com/20856381/47619487-74fb7980-dadf-11e8-84c7-6127f572f4fb.png)


https://maputnik.github.io/editor/?style=https://maputnik.github.io/osm-liberty/style.json#19/44.4279453/8.883408/48.5/44
