### ISSUE TITLE
Maptiler key broken

### ISSUE THREAD

**Issue by kylebarron** [lukasmartinelli/osm-liberty#68]
The maptiler key for displaying through web Maputnik is presumably broken. When I get to the end of the Natural Earth layers, it's just blank:
![image](https://user-images.githubusercontent.com/15164633/71451565-5a01b500-2736-11ea-8a8b-99d6ad71c04d.png)

**Comment by pathmapper** [comment]
Maybe only a temporary issue, for me it is working fine:

https://maputnik.github.io/editor/#5.94/46.327/-120.533

![grafik](https://user-images.githubusercontent.com/20856381/71467167-42700e00-27c2-11ea-9a96-00475e02fc4c.png)

Could you please check if the issue persists on your side @kylebarron ?
If this still isn't working for you, please open an issue on the editor's repository (https://github.com/maputnik/editor/issues), the fallback keys are handled there.

**Comment by kylebarron** [comment]
Sorry, [privacybadger](https://github.com/EFForg/privacybadger) has had a ton of false positives recently, and I didn't remember to check that before submitting
