### ISSUE TITLE
Wetlands styling

### ISSUE THREAD

**Issue by kylebarron** [lukasmartinelli/osm-liberty#70]
I noticed some disconnected streams (center of image), and discovered that it's because wetlands aren't currently given any styling.
https://maputnik.github.io/editor/#15.27/44.10019/-71.576018
![image](https://user-images.githubusercontent.com/15164633/71488515-385c0880-27de-11ea-8dd6-c46f03a5b2df.png)

This is defined as `class=wetlands` within `landcover` in the OpenMapTiles schema [(And as `natural=wetland` within OSM)](https://www.openstreetmap.org/way/714412426):
![image](https://user-images.githubusercontent.com/15164633/71488530-4e69c900-27de-11ea-9485-f0ebb6923636.png)

The default OSM basemap uses a custom pattern:
![image](https://user-images.githubusercontent.com/15164633/71488618-bddfb880-27de-11ea-9523-f97418491262.png)

Should these polygons be given a style in OSM Liberty, and if so, what should it be?

**Comment by pathmapper** [comment]
Nice find @kylebarron

> Should these polygons be given a style in OSM Liberty, and if so, what should it be?

Yes, we should style these. Currently we are using only a pattern for the `road_area_pattern`, for wetlands maybe using a light plain color or a sparse pattern which is less obtrusive? 

Open for suggestions.

**Comment by kylebarron** [comment]
Maki does have a wetland icon:
https://github.com/mapbox/maki/blob/master/icons/wetland-11.svg

It doesn't look very good to just add the wetland icon in the current sprite:
![image](https://user-images.githubusercontent.com/15164633/72008012-ef19a900-3220-11ea-8423-5ca8838dd318.png)

A simple wetland icon without the bordering circle might look good, but I haven't figured out how to edit the sprite yet.

**Comment by pathmapper** [comment]
There is a Maki editor: https://labs.mapbox.com/maki-icons/editor/
Or you could use https://inkscape.org to modify the SVG.

There is no need that it would be part of the iconset, because it is no POI. We are having also SVGs which are not part of the iconset, like the fill pattern for the pedestrian_polygon:
https://github.com/maputnik/osm-liberty/tree/gh-pages/svgs/svgs_not_in_iconset

**Comment by pathmapper** [comment]
from: https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-fill-pattern

> For seamless patterns, image width and height must be a factor of two (2, 4, 8, ..., 512)

**Comment by pathmapper** [comment]
> I haven't figured out how to edit the sprite yet

You could use https://github.com/mapbox/spritezero-cli, it is described here (bottom of that page):
https://github.com/maputnik/osm-liberty#icon-design

**Comment by jpbede** [comment]
What do you say about that ?

![image](https://user-images.githubusercontent.com/3989428/80291509-4a2ec780-874e-11ea-8597-be334cb48db4.png)

**Comment by pathmapper** [comment]
Hey @jpbede, thanks, looks promising!

Would you like to submit a PR so we could evaluate how the pattern behaves for different zoom levels?

**Comment by jpbede** [comment]
Sure. Created the [PR 84](https://github.com/maputnik/osm-liberty/pull/84)
