### ISSUE TITLE
Add script to format and validate the style

### ISSUE THREAD

**Issue by kylebarron** [lukasmartinelli/osm-liberty#73]
As a possible workaround to the JSON formatting issues mentioned in https://github.com/maputnik/osm-liberty/pull/66 and https://github.com/maputnik/editor/issues/591, it might be easiest to just add `gl-style-format` in place as a Git pre-commit hook. It should be as simple as adding an NPM `package.json` with a couple dev dependencies, e.g. https://github.com/nst-guide/osm-liberty-topo/commit/75b0657c8db43c850a57eb0fca27bb1f95316a3c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R24-R32
(for now, that only validates, not formats in place)

Before writing up a PR, just wanted to check if this is of interest.

**Comment by pathmapper** [comment]
Thanks for your suggestion @kylebarron  

In general I'm up for adding a `package.json` with `@mapbox/mapbox-gl-style-spec` as dev dependency to have `gl-style-format` available.

If we would use a Git pre-commit hook, than the style would only be formatted when doining a commit, right?

I think it would be useful to be able to format/validate the style any time while working on it. 

What do you think about using a script instead which could be execute with e.g. `npm run test` to format/validate the style?

Later we could also add functionality to remove not needed default values which are bloating the style like `"visibility": "visible"` as this is a recurring request to remove them from PRs (see https://github.com/maputnik/osm-liberty/pull/61, https://github.com/maputnik/osm-liberty/pull/72#discussion_r365319078, https://github.com/maputnik/osm-liberty/pull/71#pullrequestreview-340300673).

**Comment by kylebarron** [comment]
Correct, the style would only be formatted on commit. 

I agree that format/validation at any time is good, however most of the time people will be making edits using Maputnik, which probably enforces a valid style, and with the online editor forces formatting correctly. I mostly see this as a workaround/second check while the Maputnik issue is being sorted out.

**Comment by pathmapper** [comment]
OK thanks, so let's implement this with a `npm run ...` script which could be executed at any time.

Yeah, this is a good workaround for people using Maputnik Desktop, but also generally useful (e.g. when modifying the style with a text editor).

Is this something you are interested to work on and submit a PR?

**Comment by pathmapper** [comment]
ref: https://github.com/maputnik/osm-liberty/pull/59#issuecomment-541316460
