### ISSUE TITLE
How to create the sprite sheets?

### ISSUE THREAD

**Issue by abenrob** [lukasmartinelli/osm-liberty#8]
How are you creating the sprite sheets for the style once you have downloaded the individual svgs?

**Comment by abenrob** [comment]
ping.
I have modified the liberty style, but the last piece is the icon sprites. 
Is there a tool you are using to take the sprites downloaded from the maki editor, and build the png sprite sheet and corresponding json reference?

**Comment by lukasmartinelli** [comment]
There is spritezero.
https://github.com/mapbox/spritezero/blob/master/README.md

Can give you a more detailed answer on friday.

**Comment by abenrob** [comment]
Great! Thanks. I got the sprites to build with spritezero (from my maki editor download) just need to know how to incorporate your custom sprites. 
I'd be happy to PR the process/documentation once you have it set, if that helps.

**Comment by lukasmartinelli** [comment]
Added instructions to README
