### ISSUE TITLE
aerial tramways have airport icon

### ISSUE THREAD

**Issue by abenrob** [lukasmartinelli/osm-liberty#9]
![zermatt_aerial_tramways](https://cloud.githubusercontent.com/assets/3422185/20829517/b0bea7da-b87c-11e6-80d0-35ba4178c1d1.png)

**Comment by orangemug** [comment]
<img width="474" alt="screen shot 2018-02-25 at 10 00 50" src="https://user-images.githubusercontent.com/235915/36640245-d9391d82-1a12-11e8-8bf8-60d7d938271a.png">

@abenrob this looks to be correct now
