### ISSUE TITLE
Minor roads are over tertiaries

### ISSUE THREAD

**Issue by pyrog** [lukasmartinelli/osm-liberty#90]
https://maputnik.github.io/editor/#19.04/50.8340273/2.2143449

<img width="33%" alt="osm-liberty" src="https://user-images.githubusercontent.com/2158081/97912230-d0a31200-1d4c-11eb-81b3-f0fab7a35444.png"> <img width="33%" alt="Bright" src="https://user-images.githubusercontent.com/2158081/97912218-ce40b800-1d4c-11eb-94cb-0a304f103bc6.png">

**Comment by pathmapper** [comment]
Thanks for reporting this @pyrog, fixed in #93.

**Comment by pyrog** [comment]
Thank you very much 😃
