### ISSUE TITLE
Add rendering for place=quarter

### ISSUE THREAD

**Issue by jdhoek** [lukasmartinelli/osm-liberty#92]
OSM Liberty currently renders `place=neighbourhood` and `place=suburb`, but not the intermediate `place=quarter` ([OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:place%3Dquarter)). I have opened an issue at OpenMapTiles (https://github.com/openmaptiles/openmaptiles/issues/1064) to add `place=quarter` there as well.

OSM Liberty only uses the words `neighbourhood` and `suburb` in one place in `style.json`. Is it sufficient to add `quarter` there or is more needed for rendering?

OSM Liberty is used by the OSM-based website [knooppuntnet.nl](https://knooppuntnet.nl/en/map/hiking) and I would like to fix the lack of `place=quarter` labels there (https://github.com/vmarc/knooppuntnet/issues/136). Of course, as `place=quarter` is an established tag with over 40,000 uses it should benefit all users of this style.

**Comment by pathmapper** [comment]
Hi @jdhoek,

> Is it sufficient to add quarter there or is more needed for rendering?

We need to have `place=quarter` available in the OpenMapTiles vector tiles used for rendering of the style.
If this should be the case in the future, we could think about a good way to include `place=quarter` in OSM Liberty.

**Comment by jdhoek** [comment]
I have opened https://github.com/openmaptiles/openmaptiles/issues/1064 for that purpose.

**Comment by pathmapper** [comment]
Note: https://github.com/openmaptiles/openmaptiles/pull/1065 will be included in OMT v3.13
